# minitest specifics
AllCops:
  TargetRubyVersion: 2.2
  Exclude:
    - Dangerfile
Metrics/LineLength:
  Max: 119
Metrics/MethodLength:
  Exclude:
    - test/**/*
Metrics/ClassLength:
  Exclude:
    - lib/request_handler/base.rb
Style/ClassAndModuleChildren:
  Exclude:
    - test/**/*

Metrics/BlockLength:
  Enabled: false
Style/Documentation:
  Enabled: false
