inherit_from: .rubocop_todo.yml

# minitest specifics
require:
  - rubocop-rake
  - rubocop-rspec
  - rt_rubocop_defaults

AllCops:
  TargetRubyVersion: 2.6
  Exclude:
    - Dangerfile

Gemspec/DevelopmentDependencies:
  EnforcedStyle: gemspec


Metrics/ClassLength:
  Exclude:
    - lib/request_handler/base.rb
